language: node_js
node_js:
- '12.0.0'
cache: yarn
script:
- yarn --version
- yarn check --integrity
- yarn test

deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: kuNyS8eL3jOH6t6ic5v84h71h9qJuLIKw1I1kyEY6taM498Z7zczTQZr29FLpW01U/AWmWKBqWv86jDwNSF79yHkAdeU/TGtC4GQNDjCSbt26G6YIy0qxA6ZnwlLM50e5UaTBIzAtj7zns72KufOl9X6+KkRFGelXUBSZ+b6YegIpJYC5t8d89xhgLYa2jdtaoIKnB+ANKThx0pX8wozYKJ+twM/Kktz22YNEipWw0GaAQJeEQD+5K7YJywYMRIPf41bKeTPHZz+yoA0Y4WTUZ54miH405O2Tn8m4Pw0EQa9mGhjkPQYvPEDE6eKQ5A9kMc6enu6ybaA/ZW4VwM/wvoj/d7VEh4ZLlLwgJSq3tB0KgQDg68lduUXDGDXcZdX8P8jXW2rt58RuyNrwNvXd+ygdt9hPIJ0Kdd86IrY3RwhGDAKWLXAA4gIac3/0mmQgvz6+FnR3SheEFpJKA7Ntxo5h+/2vs5L9tarlBEW0KjBrEYV3aVptW30HsKwX9kGic6AtaZGfdDWwR2qVvz3XKCW2w6YZCfEQN6JZ7Ku0l+7tOOwkewjjvgOrQlaFvg8rjz2ENyQAWtKY0WSuJXwOAc+9p3dbxLgg16Wb01Y9dLBjlMfUbTOcS65R1pyQUqqRUVzC150Jvz2BIWqia1bY4amKssJqmUp1fB6cVVy2mU=
  on:
    tags: true
    repo: hmcts/div-pay-client
